// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/admin/v1/admin.proto

package adminv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClusterStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterStatusRequest) Reset() {
	*x = ClusterStatusRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStatusRequest) ProtoMessage() {}

func (x *ClusterStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStatusRequest.ProtoReflect.Descriptor instead.
func (*ClusterStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

type GroupStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         uint64                 `protobuf:"varint,1,opt,name=group,proto3" json:"group,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId      uint64                 `protobuf:"varint,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"` // this node's role in the group
	CommitIndex   uint64                 `protobuf:"varint,5,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	LastApplied   uint64                 `protobuf:"varint,6,opt,name=last_applied,json=lastApplied,proto3" json:"last_applied,omitempty"`
	LastLogIndex  uint64                 `protobuf:"varint,7,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	Members       map[uint64]string      `protobuf:"bytes,8,rep,name=members,proto3" json:"members,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // id -> address
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupStatus) Reset() {
	*x = GroupStatus{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupStatus) ProtoMessage() {}

func (x *GroupStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupStatus.ProtoReflect.Descriptor instead.
func (*GroupStatus) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *GroupStatus) GetGroup() uint64 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *GroupStatus) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *GroupStatus) GetLeaderId() uint64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *GroupStatus) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GroupStatus) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *GroupStatus) GetLastApplied() uint64 {
	if x != nil {
		return x.LastApplied
	}
	return 0
}

func (x *GroupStatus) GetLastLogIndex() uint64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *GroupStatus) GetMembers() map[uint64]string {
	if x != nil {
		return x.Members
	}
	return nil
}

type ClusterStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint64                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Groups        []*GroupStatus         `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterStatusResponse) Reset() {
	*x = ClusterStatusResponse{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStatusResponse) ProtoMessage() {}

func (x *ClusterStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStatusResponse.ProtoReflect.Descriptor instead.
func (*ClusterStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ClusterStatusResponse) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *ClusterStatusResponse) GetGroups() []*GroupStatus {
	if x != nil {
		return x.Groups
	}
	return nil
}

// Membership changes apply to every Raft group on the affected node:
// shards share the same member set (placement is static until
// rebalancing exists).
type AddMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberRequest) Reset() {
	*x = AddMemberRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberRequest) ProtoMessage() {}

func (x *AddMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberRequest.ProtoReflect.Descriptor instead.
func (*AddMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *AddMemberRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddMemberRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type AddMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberResponse) Reset() {
	*x = AddMemberResponse{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberResponse) ProtoMessage() {}

func (x *AddMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberResponse.ProtoReflect.Descriptor instead.
func (*AddMemberResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{4}
}

type RemoveMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveMemberRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RemoveMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberResponse) Reset() {
	*x = RemoveMemberResponse{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberResponse) ProtoMessage() {}

func (x *RemoveMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveMemberResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{6}
}

type TransferLeadershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         uint64                 `protobuf:"varint,1,opt,name=group,proto3" json:"group,omitempty"`
	To            uint64                 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferLeadershipRequest) Reset() {
	*x = TransferLeadershipRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferLeadershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferLeadershipRequest) ProtoMessage() {}

func (x *TransferLeadershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferLeadershipRequest.ProtoReflect.Descriptor instead.
func (*TransferLeadershipRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *TransferLeadershipRequest) GetGroup() uint64 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *TransferLeadershipRequest) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

type TransferLeadershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferLeadershipResponse) Reset() {
	*x = TransferLeadershipResponse{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferLeadershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferLeadershipResponse) ProtoMessage() {}

func (x *TransferLeadershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferLeadershipResponse.ProtoReflect.Descriptor instead.
func (*TransferLeadershipResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{8}
}

var File_proto_admin_v1_admin_proto protoreflect.FileDescriptor

const file_proto_admin_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/admin/v1/admin.proto\x12\badmin.v1\"\x16\n" +
	"\x14ClusterStatusRequest\"\xce\x02\n" +
	"\vGroupStatus\x12\x14\n" +
	"\x05group\x18\x01 \x01(\x04R\x05group\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x03 \x01(\x04R\bleaderId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12!\n" +
	"\fcommit_index\x18\x05 \x01(\x04R\vcommitIndex\x12!\n" +
	"\flast_applied\x18\x06 \x01(\x04R\vlastApplied\x12$\n" +
	"\x0elast_log_index\x18\a \x01(\x04R\flastLogIndex\x12<\n" +
	"\amembers\x18\b \x03(\v2\".admin.v1.GroupStatus.MembersEntryR\amembers\x1a:\n" +
	"\fMembersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"_\n" +
	"\x15ClusterStatusResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\x12-\n" +
	"\x06groups\x18\x02 \x03(\v2\x15.admin.v1.GroupStatusR\x06groups\"<\n" +
	"\x10AddMemberRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\x13\n" +
	"\x11AddMemberResponse\"%\n" +
	"\x13RemoveMemberRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x16\n" +
	"\x14RemoveMemberResponse\"A\n" +
	"\x19TransferLeadershipRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\x04R\x05group\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\x04R\x02to\"\x1c\n" +
	"\x1aTransferLeadershipResponse2\xcf\x02\n" +
	"\x05Admin\x12P\n" +
	"\rClusterStatus\x12\x1e.admin.v1.ClusterStatusRequest\x1a\x1f.admin.v1.ClusterStatusResponse\x12D\n" +
	"\tAddMember\x12\x1a.admin.v1.AddMemberRequest\x1a\x1b.admin.v1.AddMemberResponse\x12M\n" +
	"\fRemoveMember\x12\x1d.admin.v1.RemoveMemberRequest\x1a\x1e.admin.v1.RemoveMemberResponse\x12_\n" +
	"\x12TransferLeadership\x12#.admin.v1.TransferLeadershipRequest\x1a$.admin.v1.TransferLeadershipResponseB:Z8github.com/Abhijeetgupta55/raftkv/proto/admin/v1;adminv1b\x06proto3"

var (
	file_proto_admin_v1_admin_proto_rawDescOnce sync.Once
	file_proto_admin_v1_admin_proto_rawDescData []byte
)

func file_proto_admin_v1_admin_proto_rawDescGZIP() []byte {
	file_proto_admin_v1_admin_proto_rawDescOnce.Do(func() {
		file_proto_admin_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_admin_v1_admin_proto_rawDesc), len(file_proto_admin_v1_admin_proto_rawDesc)))
	})
	return file_proto_admin_v1_admin_proto_rawDescData
}

var file_proto_admin_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_admin_v1_admin_proto_goTypes = []any{
	(*ClusterStatusRequest)(nil),       // 0: admin.v1.ClusterStatusRequest
	(*GroupStatus)(nil),                // 1: admin.v1.GroupStatus
	(*ClusterStatusResponse)(nil),      // 2: admin.v1.ClusterStatusResponse
	(*AddMemberRequest)(nil),           // 3: admin.v1.AddMemberRequest
	(*AddMemberResponse)(nil),          // 4: admin.v1.AddMemberResponse
	(*RemoveMemberRequest)(nil),        // 5: admin.v1.RemoveMemberRequest
	(*RemoveMemberResponse)(nil),       // 6: admin.v1.RemoveMemberResponse
	(*TransferLeadershipRequest)(nil),  // 7: admin.v1.TransferLeadershipRequest
	(*TransferLeadershipResponse)(nil), // 8: admin.v1.TransferLeadershipResponse
	nil,                                // 9: admin.v1.GroupStatus.MembersEntry
}
var file_proto_admin_v1_admin_proto_depIdxs = []int32{
	9, // 0: admin.v1.GroupStatus.members:type_name -> admin.v1.GroupStatus.MembersEntry
	1, // 1: admin.v1.ClusterStatusResponse.groups:type_name -> admin.v1.GroupStatus
	0, // 2: admin.v1.Admin.ClusterStatus:input_type -> admin.v1.ClusterStatusRequest
	3, // 3: admin.v1.Admin.AddMember:input_type -> admin.v1.AddMemberRequest
	5, // 4: admin.v1.Admin.RemoveMember:input_type -> admin.v1.RemoveMemberRequest
	7, // 5: admin.v1.Admin.TransferLeadership:input_type -> admin.v1.TransferLeadershipRequest
	2, // 6: admin.v1.Admin.ClusterStatus:output_type -> admin.v1.ClusterStatusResponse
	4, // 7: admin.v1.Admin.AddMember:output_type -> admin.v1.AddMemberResponse
	6, // 8: admin.v1.Admin.RemoveMember:output_type -> admin.v1.RemoveMemberResponse
	8, // 9: admin.v1.Admin.TransferLeadership:output_type -> admin.v1.TransferLeadershipResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_admin_v1_admin_proto_init() }
func file_proto_admin_v1_admin_proto_init() {
	if File_proto_admin_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_admin_v1_admin_proto_rawDesc), len(file_proto_admin_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_admin_v1_admin_proto_goTypes,
		DependencyIndexes: file_proto_admin_v1_admin_proto_depIdxs,
		MessageInfos:      file_proto_admin_v1_admin_proto_msgTypes,
	}.Build()
	File_proto_admin_v1_admin_proto = out.File
	file_proto_admin_v1_admin_proto_goTypes = nil
	file_proto_admin_v1_admin_proto_depIdxs = nil
}
